version: '3.8'

services:
  api:
    build:
      context: .          # root of the repo
      dockerfile: docker/Dockerfile  # explicitly point to your Dockerfile
    container_name: sales-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

  dashboard:
    image: python:3.9-slim
    container_name: sales-dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      python scripts/download_dataset.py &&
      jupyter nbconvert --to notebook --execute notebooks/eda_modeling.ipynb --inplace &&
      streamlit run app/dashboard.py --server.port 8501 --server.address 0.0.0.0
      "
    depends_on:
      - api
