apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
  namespace: sales-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      containers:
        - name: sales-api
          image: sales-api:latest   # <- we'll build this into Minikube
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
  namespace: sales-forecast
spec:
  selector:
    app: sales-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

